image:
  repository: ghcr.io/tryuuu/csi-driver
  tag: "v0.1.0"
  pullPolicy: IfNotPresent

sidecars:
  externalProvisioner:
    image: registry.k8s.io/sig-storage/csi-provisioner:v5.1.0
  externalResizer:
    image: registry.k8s.io/sig-storage/csi-resizer:v1.12.0
  nodeDriverRegistrar:
    image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.12.0

storageClass:
  name: csi-local
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
  allowVolumeExpansion: true

namespace: csi-driver

socketPath: /csi/csi.sock
kubeletDir: /var/lib/kubelet
